
version: 2

jobs:
  build:
    docker:
      - image: nixos/nix:2.3
    steps:
      - checkout
      - run:
          name: Pull submodules
          command: |
            nix-env --install git
            git submodule init
            git submodule update --remote
      - run:
          name: Build
          command: nix-build --arg enableProfiling false

